name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          # Verify installation
          allure --version

      - name: Install Chrome and ChromeDriver
        run: |
          # Remove any existing Chrome installations
          sudo apt-get remove -y google-chrome-stable
          sudo apt-get autoremove -y

          # Add Google Chrome repository
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list

          # Update and install Chrome
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          # Verify Chrome installation
          google-chrome --version

          # Clean up any existing ChromeDriver
          sudo rm -f /usr/local/bin/chromedriver
          sudo rm -f /usr/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=./allure-results

      - name: Generate Allure report
        run: |
          allure generate --clean ./allure-results -o ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 30

      - name: Run tests
        run: |
          python -m pytest tests/ -v

      - name: Generate Allure report
        run: |
          allure generate --clean

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            test-results.xml
            allure-results/

      - name: Publish Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          report_name: Test Report
